spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aws_project01
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
aws:
  region: us-east-2
  sns:
    topic:
      product:
        events:
          arn: product-events

  s3:
    bucket:
      invoice:
        name: pcs-invoice

  sqs:
    queue:
      invoice:
        events:
          name: s3-invoice-events